---

#
# Perform system upgrade on all inventory hosts.
#

- hosts: servers
  remote_user: root
  tasks:
    - block:

        - name: Updating APT cache
          apt: update_cache=yes

        - name: Upgrading all installed packages
          apt: upgrade=yes

      when: ansible_os_family == 'Debian'
